apiVersion: v1
kind: Pod
metadata:
  name: pod-cm
spec:
  containers:
  - name: my-cm-pod
    image: nginx
    env:
      - name: PASSWORD
        valueFrom:
          configMapKeyRef:
            name: my-cm
            key: PASSWORD

      - name: USERNAME
        valueFrom:
          configMapKeyRef:
            name: my-cm
            key: USERNAME
